markdown: kramdown
placeholder:
  - img_url: placeholder.jpg
    name: You
    placeholder: true
    bio: If you think we're doing a right thing and want to contribute, be sure to drop us a line at kottans.org@gmail.com
    # github: https://github.com/join
    # twitter: https://twitter.com/signup
regulars:
  coach: &sergey
    img_url: serg.jpg
    name: Sergey Gopkalo
    lang: ruby
    # bio: Total of 10 years experience in IT, 5 years experience as software developer, about 3 years as Ruby developer…
    # github: TOADD
    # twitter: TOADD
  coach: &rubycat
    img_url: lena.jpg
    name: Elena Morgun
    lang: ruby
    # bio: Cat that loves Ruby and Rails…
    github: darthrevan
    twitter: rubykatze
  coach: &johny
    img_url: john.jpg
    name: Oleksandr Lapshyn
    lang: js
    # bio: Front-end developer that passionates about open-source and human interaction…
    github: sudodoki
    twitter: sudodoki
  coach: &artem
    img_url: such.jpg
    name: Artem Sychov
    lang: ruby, js, python
    # bio: Deeply curious, loves to learn, insightful about people and their psychological make-up, deft in communication, excel at networking, deeply tech-savvy and enjoys growing others through education and leadership
    github: suchov
    twitter: ArtemSuchov
  coach: &julia
    img_url: julia.jpg
    name: Julia Budnik
    lang: ruby, js
    # bio: 7 badass years in IT. Dictator in css/html/life domains
    github: mayosh
    twitter: Jubudni
  coach: &den
    img_url: den.jpg
    name: Denis Yagofarov
    lang: ruby
    # bio: 7 year-long journey into IT, 4 years experience as system and network administrator, about 2 years as Ruby developer
    github: denyago
    twitter: denyago
  coach: &bortnyk
    img_url: misha.jpg
    name: Mikhail Bortnyk
    lang: ruby, js
    #bio: Ruby on Rails developer that has a passion for BDD and elegant solutions…
    github: vessi
    twitter: mikhailbortnyk
  coach: &lulia
    img_url: lulya.jpg
    name: Julia Savinkova
    # bio: Sometimes people think she's too sweet to be a programmer & hardcore geek. .NET/JavaScript Developer, TDD adept
    lang: js
    github: programulya
    twitter: programulya
  coach: &listochkin
    name: Andrey Listochkin
    img_url: listochkin.jpg
    lang: js
    github: listochkin
    twitter: listochkin
years:
  - year: 2015-2016
    coaches:

    # .NET 2015-2016 November-March
    - <<: *bortnyk
      lang: erlang
    - <<: *lulia
      lang: C#, js
    - full_img_url: https://media.licdn.com/mpr/mpr/shrinknp_400_400/p/4/000/134/1db/19bee7c.jpg
      name: Valentine Radchuk
      lang: C#
      github: zaknafeyn
      twitter: zzaknafeyn
    - full_img_url: https://media.licdn.com/mpr/mpr/shrinknp_400_400/p/8/005/016/03f/257db29.jpg
      name: Alexey Aza
      lang: C#
      github: jalaz
      twitter: jalazVS
    - full_img_url: https://avatars3.githubusercontent.com/u/7375145?v=3&s=460
      name: Dmytro Hnatiuk
      lang: C#
      github: hnatiukdm
      twitter: dhnatiuk
    - full_img_url: http://i.imgur.com/M8eFqNY.jpg
      name: Dan Kashkovsky
      lang: C#
      github: Mr-Zoidberg
      twitter: danniekash
      is_guest: true
    - full_img_url: http://i.imgur.com/qxFREI6.jpg
      name: Serhiy Kalinets
      lang: C#
      github: skalinets
      twitter: skalinets
      is_guest: true
    # .NET 2016 March-July
    - full_img_url: http://i.imgur.com/rY9hMRc.jpg
      name: Timur Mudzhyri
      lang: C#
      github: intrueder
      twitter: intrueder
    - full_img_url: http://i.imgur.com/Sxy9of8.png
      name: Roman Vovk
      lang: C#
      github: kakarotto67
      twitter: roman_vovk1
    - *artem
    # JS 2016 March-July
    # Kyiv
    - name: Aleksey Shvayka
      lang: js
      github: shvaikalesh
    - name: Nikolay Kozhukharenko
      lang: js
      github: mkozhukharenko
    - full_img_url: https://dl.dropboxusercontent.com/s/yt6tpuxmgt7bp54/11492412.jpeg
      name: Ivan Stetsenko
      lang: js
      github: firec0der
    - *johny
    - name: Illia Seheda
      lang: js
      github: ALF-er
      is_guest: true
    - name: Artem Bey
      lang: js
      github: defly
      is_guest: true
    - *listochkin
    - full_img_url: taras.jpg
      name: Taras Hupalo
      lang: js
      github: cwayfinder
      is_guest: true
    # Kharkiv
    - full_img_url: https://pp.vk.me/c626517/v626517438/5e37/5tQ3gY3KSvw.jpg
      name: Illya Klymov
      lang: js
      github: xanf
    # Lviv
    - name: Ivan Lavriv
      lang: js
      twitter: ilavriv
      github: lavriv92
      full_img_url: https://scontent-vie1-1.xx.fbcdn.net/v/t1.0-9/13524357_1141337539262841_8174019877116492080_n.jpg?oh=a146ccebf4bad5f6e544e8e5caac1a7a&oe=581F19AB
    - name: Serg Bataev
      lang: js
      twitter: servika
      full_img_url: https://pbs.twimg.com/profile_images/506726680845492224/7rkCi3eK.jpeg
    - name: Denis Stoyanov
      lang: js
      twitter: xgrommx
      github: xgrommx
      is_guest: true

  - year: 2014-2015
    coaches:
    - img_url: placeholder.jpg
      name: Eugene Safronov
      full_img_url: https://pbs.twimg.com/profile_images/2566448984/9q4civlcn3xyda9vpc48.jpeg
      lang: js
      # bio: Nice guy
      github: sejoker
      twitter: sejoker
    - full_img_url: https://pbs.twimg.com/profile_images/637086673281527808/-ee20k4R_400x400.jpg
      name: Andrey Savchenko
      lang: Ruby
      github: ptico
      twitter: ptico
    - *sergey
    - *rubycat
    - *bortnyk
    - *johny
    - *artem
    - *julia
    - full_img_url: http://aejis.eu/img/supermen/ds.jpg
      name: Denis Sergienko
      lang: ruby, js
      # bio:
      github: ololyay
      twitter: ololyay
    - name: Igor Kroosh
      full_img_url: https://pbs.twimg.com/profile_images/461954738762682368/_Rf9eX4S.jpeg
      lang: ruby, js
      # bio:
      github: tilast
      twitter: ikroosh
    - name: Ingvar Stepanyan
      full_img_url: https://pbs.twimg.com/profile_images/517329577580826624/u42jHnsA.jpeg
      lang: js
      is_guest: true
      github: RReverser
      twitter: RReverser
    - name: Max Klymyshyn
      full_img_url: https://avatars3.githubusercontent.com/u/276682?v=3&s=400
      lang: js
      is_guest: true
      github: joymax
      twitter: maxmaxmaxmax
    - name: Victor Sych
      full_img_url: https://avatars2.githubusercontent.com/u/2924275?v=3&s=400
      lang: js
      is_guest: true
      github: vsych
      twitter: VictorSych
    - name: Viktor Zozulyak
      img_url: zuzusik.jpg
      lang: js
      is_guest: true
      github: zuzusik
    - *listochkin

  - year: 2013-2014
    coaches:
    - *sergey
    - *den
    - <<: *rubycat
      lang: ruby, js
    - <<: *bortnyk
      lang: ruby, js
    - <<: *johny
      lang: ruby, js
    - full_img_url: https://avatars3.githubusercontent.com/u/307982?v=3&s=400
      name: Alex Rozumii
      lang: ruby
      github: brain-geek
      twitter: brain_geek
    - *artem
    - *julia
    - *lulia
    - name: Alexander Beletsky
      full_img_url: https://pbs.twimg.com/profile_images/660058232338178048/4n45I5Xw_400x400.jpg
      lang: js
      is_guest: true
      github: alexbeletsky
      twitter: alexbeletsky
    - name: Eldar Djafarov
      full_img_url: https://pbs.twimg.com/profile_images/971019265/25-08-08_1708.jpg
      img_url: placeholder.jpg
      lang: js
      github: edjafarov
      twitter: edjafarov
    - *listochkin
    - name: Artyom Trityak
      full_img_url: https://avatars2.githubusercontent.com/u/957406?v=3&s=400
      lang: js
      is_guest: true
      github: ArtyomTrityak
      twitter: ArtyomTrityak
    - name: Valentyn Shybanov
      full_img_url: https://avatars1.githubusercontent.com/u/459897?v=3&s=400
      lang: js
      is_guest: true
      github: olostan
      twitter: olostan
    - name: Dmytro Yarmak
      full_img_url: https://avatars1.githubusercontent.com/u/1378201?v=3&s=400
      lang: js
      github: dmytroyarmak
      twitter: dmytroyarmak
    - name: Eugene Koshevoy
      img_url: placeholder.jpg
      lang: js
      is_guest: true
      # github: TODOADD
      # twitter: TODOADD
    - name: Dmitry Tselinko
      img_url: dmitry.jpg
      lang: js
      # bio: Kick-ass javascript knowledge helps Dmitry with his daily job & night shifts with Kottans (ocassionaly)…
      github: dmitryt
      # twitter: TODOADD
    - name: Dmitriy Filipenko
      full_img_url: https://avatars3.githubusercontent.com/u/1822520?v=3&s=400
      lang: js
      github: dmfilipenko
      twitter: dmfilipenko

  - year: 2012-2013
    coaches:
    - *den
    - *bortnyk
    - *artem

  - year: 2011-2012
    coaches:
    - *bortnyk
    - *artem
    - img_url: alex.jpg
      name: Alexandr Shilo
      lang: ruby
